//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Day
    {
        public Day()
        {
            this.ClassesSchedules = new HashSet<ClassesSchedule>();
        }
    
        public int DayID { get; set; }
        public string DayName { get; set; }
    
        public virtual ICollection<ClassesSchedule> ClassesSchedules { get; set; }
    }
}
