//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.StudentClasses = new HashSet<StudentClass>();
            this.StudentsParents = new HashSet<StudentsParent>();
        }
    
        public int StudentID { get; set; }
        public System.DateTime DOB { get; set; }
        public string HomePhone { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public Nullable<System.DateTime> ExpectedGraduationDate { get; set; }
        public int FormID { get; set; }
        public int SchoolCode { get; set; }
        public int VillageID { get; set; }
        public int ParishID { get; set; }
        public string PriorEducation { get; set; }
        public string Email { get; set; }
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string M_I_ { get; set; }
        public string LastName { get; set; }
    
        public virtual Parish Parish { get; set; }
        public virtual SchoolForm SchoolForm { get; set; }
        public virtual School School { get; set; }
        public virtual ICollection<StudentClass> StudentClasses { get; set; }
        public virtual User User { get; set; }
        public virtual Village Village { get; set; }
        public virtual ICollection<StudentsParent> StudentsParents { get; set; }
    }
}
