//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public Term()
        {
            this.Classes = new HashSet<Class>();
        }
    
        public int TermID { get; set; }
        public string TermName { get; set; }
    
        public virtual ICollection<Class> Classes { get; set; }
    }
}
