//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Village
    {
        public Village()
        {
            this.AdministrativeStaffs = new HashSet<AdministrativeStaff>();
            this.Schools = new HashSet<School>();
            this.Students = new HashSet<Student>();
            this.Teachers = new HashSet<Teacher>();
            this.Principals = new HashSet<Principal>();
        }
    
        public int VillageID { get; set; }
        public string VillageName { get; set; }
    
        public virtual ICollection<AdministrativeStaff> AdministrativeStaffs { get; set; }
        public virtual ICollection<School> Schools { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
        public virtual ICollection<Principal> Principals { get; set; }
    }
}
